### ISSUE TITLE
Add module - generate manifest template

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/dcamodules#9]
AC:
- ~~Pop up message if there is no files and the selected data type is file-base.~~
- [x] Click button to generate google sheet link
- [x] Display link and click link to google sheet
-  ~~refactor DCA to use this module~~

**Comment by milen-sage** [comment]
Let's handle the warnings in a separate issue.

**Comment by milen-sage** [comment]
Closing this issue requires adding documentation for the module.
